AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Create necessary resources for markdown-inline-svg project.

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: lambda.handler
      Runtime: python3.13
      Timeout: 3
      Events:
        HttpRequest:
          Type: Api
          Properties:
            Path: /svg
            Method: get

Outputs:
  Api:
    Description: "API Gateway endpoint URL for Prod stage for function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/svg/"
  Function:
    Description: "Lambda Function ARN"
    Value: !GetAtt Function.Arn
  FunctionIamRole:
    Description: "Implicit IAM Role created for function"
    Value: !GetAtt Function.Arn
