version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "markdown-inline-svg"
s3_prefix = "markdown-inline-svg"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
